# Generated by Django 4.0.7 on 2022-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_email_remove_user_is_admin_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
