# Generated by Django 4.0.7 on 2022-09-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_last_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
