# Generated by Django 4.0.7 on 2022-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
    ]
