# Generated by Django 4.0.7 on 2022-09-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_no',
        ),
    ]
