# Generated by Django 4.0.7 on 2022-09-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
    ]
