# Generated by Django 4.0.7 on 2022-09-02 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_useraccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
