# Generated by Django 4.0.7 on 2022-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_alter_useraccount_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_no',
            field=models.CharField(default='3YN', max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
