# Generated by Django 4.0.7 on 2022-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transfer_receiver_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.CharField(max_length=120),
        ),
    ]
